name: 'Move Docker storage'
description: 'Move Docker data directory to /mnt partition for more space'
branding:
  icon: 'hard-drive'
  color: 'blue'
inputs:
  enable-move:
    description: 'Enable moving Docker data to /mnt'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Check disk space before move
      shell: bash
      run: |
        echo "=== 当前磁盘空间 ==="
        df -h
        echo "=== Docker 存储信息 ==="
        docker system df || true

    - name: Move Docker data to /mnt
      if: inputs.enable-move == 'true'
      shell: bash
      run: |
        echo "=== 移动 Docker 数据到 /mnt 分区 ==="
        
        # 停止 Docker 服务
        echo "停止 Docker 服务..."
        sudo systemctl stop docker
        
        # 清理 /mnt 下的旧数据（如果有）
        echo "清理 /mnt 下的旧数据..."
        sudo rm -rf /mnt/docker
        
        # 移动 Docker 数据到 /mnt
        echo "移动 Docker 数据..."
        if [ -d "/var/lib/docker" ]; then
          sudo mv /var/lib/docker /mnt/
          echo "成功移动现有 Docker 数据"
        else
          sudo mkdir -p /mnt/docker
          echo "创建新的 Docker 数据目录"
        fi
        
        # 创建符号链接
        echo "创建符号链接..."
        sudo ln -sf /mnt/docker /var/lib/docker
        
        # 启动 Docker 服务
        echo "启动 Docker 服务..."
        sudo systemctl start docker
        
        # 等待 Docker 启动
        sleep 5
        
        echo "Docker 数据移动完成"

    - name: Verify Docker storage
      shell: bash
      run: |
        echo "=== 验证 Docker 存储 ==="
        echo "磁盘空间:"
        df -h
        echo "Docker 根目录:"
        docker info | grep "Docker Root Dir" || echo "Docker 未运行"
        echo "符号链接:"
        ls -la /var/lib/docker
        echo "实际数据位置:"
        ls -la /mnt/docker
