name: 'Clean Docker storage'
description: 'Clean Docker data and use /mnt partition for more space'
branding:
  icon: 'hard-drive'
  color: 'blue'
inputs:
  enable-clean:
    description: 'Enable cleaning Docker data and using /mnt'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Check disk space before clean
      shell: bash
      run: |
        echo "=== 当前磁盘空间 ==="
        df -h
        echo "=== Docker 存储信息 ==="
        docker system df || true

    - name: Clean Docker data and use /mnt
      if: inputs.enable-clean == 'true'
      shell: bash
      run: |
        echo "=== 清理 Docker 数据并使用 /mnt 分区 ==="
        
        # 停止 Docker 服务
        echo "停止 Docker 服务..."
        sudo systemctl stop docker
        
        # 直接删除 Docker 数据，不移动
        echo "删除 Docker 数据..."
        sudo rm -rf /var/lib/docker
        sudo rm -rf /mnt/docker
        
        # 在 /mnt 创建新的 Docker 数据目录
        echo "在 /mnt 创建新的 Docker 数据目录..."
        sudo mkdir -p /mnt/docker
        
        # 创建符号链接指向 /mnt
        echo "创建符号链接..."
        sudo ln -sf /mnt/docker /var/lib/docker
        
        # 启动 Docker 服务
        echo "启动 Docker 服务..."
        sudo systemctl start docker
        
        # 等待 Docker 启动
        sleep 5
        
        echo "Docker 数据清理和重定向完成"

    - name: Verify Docker storage
      shell: bash
      run: |
        echo "=== 验证 Docker 存储 ==="
        echo "磁盘空间:"
        df -h
        echo "Docker 根目录:"
        docker info | grep "Docker Root Dir" || echo "Docker 未运行"
        echo "符号链接:"
        ls -la /var/lib/docker
        echo "实际数据位置:"
        ls -la /mnt/docker
