name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "registry.cn-hangzhou.aliyuncs.com"
  ALIYUN_NAME_SPACE: "githubimage"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Pull
    runs-on: ubuntu-22.04
    steps:
    # 第一步必须先检出代码
    - name: Check out code
      uses: actions/checkout@v4

    # 然后才能调用本地 Action
    - name: Maximize disk space
      uses: ./.github/actions/maximize-disk-space
      with:
        remove-docker-images: true
        remove-dotnet: true
        remove-android: true
        remove-codeql: true
        swap-size-mb: 4096

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image Aliyun
      run: |
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        
        echo "初始磁盘空间:"
        df -h
        
        count=0
        while IFS= read -r line; do
          [[ -z "$line" ]] && continue
          echo "=== 处理第 $((count+1)) 个镜像: $line ==="
          
          docker pull $line
          image=$(echo "$line" | awk '{print $NF}')
          image_name_tag=$(echo "$image" | sed 's#/#_#g')
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image_name_tag"
          
          docker tag $image $new_image
          docker push $new_image
          
          # 立即清理
          docker rmi $image $new_image || true
          docker system prune -f
          
          count=$((count+1))
          echo "当前磁盘空间:"
          df -h
          
        done < images.txt
