name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "registry.cn-hangzhou.aliyuncs.com"
  ALIYUN_NAME_SPACE: "githubimage"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Pull
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Move Docker storage to /mnt
      uses: ./.github/actions/maximize-disk-space
      with:
        enable-clean: true

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image Aliyun
      run: |
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        
        cd $GITHUB_WORKSPACE
        
        echo "开始处理镜像..."
        count=0
        while IFS= read -r line; do
          [[ -z "$line" ]] && continue
          echo "=== 处理第 $((count+1)) 个镜像: $line ==="
          
          # 拉取镜像
          docker pull $line
          
          # 重新标签
          image=$(echo "$line" | awk '{print $NF}')
          image_name_tag=$(echo "$image" | sed 's#/#_#g')
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image_name_tag"
          
          docker tag $image $new_image
          docker push $new_image
          
          # 清理本地镜像
          docker rmi $image $new_image || true
          
          count=$((count+1))
          echo "已完成 $count 个镜像"
          
        done < images.txt
        
        echo "成功处理 $count 个镜像"
